# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download makerst
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://raw.githubusercontent.com/godotengine/godot/3.2/doc/tools/makerst.py

      # Runs a set of commands using the runners shell
      - name: Export XML documentation to RST
        run: |
          mkdir wiki_api
          python3 ./makerst.py --output wiki_api/ doc_classes/ || /bin/true
          for i in wiki_api/*
          do
            sed -i -e '1d' -e 's/:ref:`\(.*\)`/`\1`_/g' $i
          done
          echo "Done"    

      - name: Publish to GitHub Wiki
        # You may pin to the exact commit or the version.
        # uses: SwiftDocOrg/github-wiki-publish-action@a87db85ed06e4431be29cfdcb22b9653881305d0
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          # A path to the directory of files to publish
          path: "wiki_api/"
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
